public static class GenerateLayers
{
	[UnityEditor.MenuItem("Joon/Generate Code File/Layers.cs")]
    static void RegenerateLayersFile()
    {
		string template =
			"// This file is autogenerated!" + 
			"\n" +"static public class Layers" + 
			"\n" + "{" +
			"\n" + "	#generateme#" + 
			"\n" + "}";
		string entryTemplate = "\tpublic const string #safename# = \"#name#\";\n";
		string outputPath = PathExtension.Combine("_Assets","Scripts","Util_safe","Generated","Layers.cs");
		
		string[] layers = UnityEditorInternal.InternalEditorUtility.layers;

		GenerateCodeFile.CreateFile(template, outputPath, entryTemplate, layers);
	}
}

