public static class GenerateTags
{
	[UnityEditor.MenuItem("Joon/Generate Code File/Tags.cs")]
	static void RegenerateTagsFile()
    {
		string template =
			"// This file is autogenerated!" + 
			"\n" +"static public class Tags" + 
			"\n" + "{" +
			"\n" + "	#generateme#" + 
			"\n" + "}";
		string entryTemplate = "\tpublic const string #safename# = \"#name#\";\n";
		string outputPath = PathExtension.Combine("_Assets","Scripts","Util_safe","Generated","Tags.cs");
		
		string[] tags =  UnityEditorInternal.InternalEditorUtility.tags;

		GenerateCodeFile.CreateFile(template, outputPath, entryTemplate, tags);
	}
}

